[package]
name = "sazid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.0"
bincode = "1.3.3"
chrono = "0.4.26"
clap = { version = "4.4.0", features = ["derive"] }
fast_log = "1.6.1"
lopdf = "0.31.0"
owo-colors = "3.5.0"
rand = "0.8.5"
reqwest = "0.11.20"
rustyline = "12.0.0"
serde = "1.0.187"
serde_json = "1.0.105"
tempdir = "0.3.7"
tempfile = "3.8.0"
tokio = "1.32.0"
