[package]
name = "voracious"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.0"
chrono = "0.4.26"
clap = "4.4.0"
fast_log = "1.6.1"
owo-colors = "3.5.0"
pdf = "0.8.1"
reqwest = "0.11.20"
serde = "1.0.187"
serde_json = "1.0.105"
tokio = "1.32.0"
