#![feature(unboxed_closures)]
[package]
name = "sazid"
version = "0.1.0"
edition = "2021"
default-run = "sazid"

[[bin]]
name = "generate_embeddings"
test = false
bench = false

[[bin]]
name = "sazid"
test = true
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
assert_cmd = { version = "2.0.12", features = ["color", "color-auto"] }
async-openai = "0.14.0"
async-recursion = "1.0.5"
backoff = { version = "0.4.0" }
better-panic = "0.3.0"
bincode = "1.3.3"
chrono = "0.4.26"
clap = { version = "4.3.4", default-features = false, features = [
  "std",
  "color",
  "help",
  "usage",
  "error-context",
  "suggestions",
  "derive",
  "cargo",
  "wrap_help",
  "unicode",
  "string",
  "unstable-styles",
] }
color-eyre = { version = "0.6.2", features = ["issue-url"] }
config = "0.13.3"
console-subscriber = "0.1.10"
crossterm = { version = "0.27.0", default-features = false, features = ["event-stream", "serde", "use-dev-tty"] }
directories = "5.0.1"
fast_log = "1.6.1"
futures = { version = "0.3.28", features = ["async-await"]}
human-panic = "1.2.0"
lazy_static = "1.4.0"
libc = "0.2.147"
log = "0.4.20"
lopdf = "0.31.0"
os_str_bytes = "6.5.1"
owo-colors = "3.5.0"
rand = "0.8.5"
ratatui = "0.23.0"
rayon = "1.7.0"
reqwest = { version = "0.11.20", features = ["blocking"] }
rustyline = "12.0.0"
serde = "1.0.187"
serde_derive = "1.0.188"
serde_json = "1.0.105"
shellexpand = "3.1.0"
signal-hook = "0.3.17"
strip-ansi-escapes = "0.2.0"
tempdir = "0.3.7"
tempfile = "3.8.0"
termion = "2.0.1"
tiktoken-rs = { version = "0.5.1", features = ["async-openai"] }
tokio = { version = "1.32.0", features = ["full", "tracing"] }
tokio-util = "0.7.8"
toml = "0.7.6"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tui-input = "0.8.0"
url = "2.4.1"
uuid = { version = "1.4.1", features = ["v4"] }
