[package]
name = "sazid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.14.0"
backoff = { version = "0.4.0", features = ["tokio"] }
bincode = "1.3.3"
chrono = "0.4.26"
clap = { version = "4.4.0", features = ["derive"] }
config = "0.13.3"
fast_log = "1.6.1"
lazy_static = "1.4.0"
lopdf = "0.31.0"
os_str_bytes = "6.5.1"
owo-colors = "3.5.0"
rand = "0.8.5"
rayon = "1.7.0"
reqwest = { version = "0.11.20", features = ["blocking"] }
rustyline = "12.0.0"
serde = "1.0.187"
serde_json = "1.0.105"
shellexpand = "3.1.0"
tempdir = "0.3.7"
tempfile = "3.8.0"
tiktoken-rs = { version = "0.5.1", features = ["async-openai"] }
tokio = "1.32.0"
toml = "0.7.6"
uuid = { version = "1.4.1", features = ["v4"] }
