[[commands]]
name = "list_files"
description = "List files in a directory."
[[commands.parameters]]
type = "object"
[[commands.parameters."properties"]]
path = { type = "string", description = "The path to the directory to list files in.", required = ["path"] }
# [[commands]]
# name = "cargo_check"
# description = "Run cargo check to get any compiler errors."
# [commands.properties."path"]
# description = "The path to the directory to list files in."
# required = ["path"]


        "commands": [{
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    },
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },
                "required": ["location"],
            },
        }]


[[commands]]
name = "get_current_weather"
description = "Get the current weather in a given location"
[parameters]
type = "object"
required = [ "location" ]
[parameters.properties]
[parameters.properties.location]
type = "string"
description = "The city and state, e.g. San Francisco, CA"
[parameters.properties.unit]
type = "string"
enum = [ "celsius", "fahrenheit" ]
