# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/app/embeddings/schema.rs"
# custom_type_derives = ["diesel::query_builder::QueryId"]
generate_missing_sql_type_definitions = false
import_types = ["diesel::sql_types::*", "pgvector::sql_types::*"]
# filter = { only_tables = [
#   "plaintexts",
#   "files",
#   "pg_vector_index_info",
# ] }

[migrations_directory]
dir = "migrations"
