version: '3.8'
services:
  pgvector:
    image: ankane/pgvector:latest
    environment:
      PG_MAJOR: '16'
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: embeddings
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
