---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/tenkai/Development/gpt/sazid/crates/runtime/grammars/git-config.so'
relocations:
  - { offsetInCU: 0x27, offset: 0x27, size: 0x8, addend: 0x0, symName: _tree_sitter_git_config, symObjAddr: 0x0, symBinAddr: 0x1FB4, symSize: 0xC }
  - { offsetInCU: 0x38, offset: 0x38, size: 0x8, addend: 0x0, symName: _tree_sitter_git_config, symObjAddr: 0x0, symBinAddr: 0x1FB4, symSize: 0xC }
  - { offsetInCU: 0x40, offset: 0x40, size: 0x8, addend: 0x0, symName: _ts_lex, symObjAddr: 0xC, symBinAddr: 0x1FC0, symSize: 0xF2C }
  - { offsetInCU: 0x67, offset: 0x67, size: 0x8, addend: 0x0, symName: _tree_sitter_git_config.language, symObjAddr: 0x1E90, symBinAddr: 0x4000, symSize: 0x0 }
  - { offsetInCU: 0x692, offset: 0x692, size: 0x8, addend: 0x0, symName: _ts_parse_table, symObjAddr: 0x1A32, symBinAddr: 0x39E6, symSize: 0x0 }
  - { offsetInCU: 0x6C1, offset: 0x6C1, size: 0x8, addend: 0x0, symName: _ts_small_parse_table, symObjAddr: 0x1470, symBinAddr: 0x3424, symSize: 0x0 }
  - { offsetInCU: 0x6E4, offset: 0x6E4, size: 0x8, addend: 0x0, symName: _ts_small_parse_table_map, symObjAddr: 0x184C, symBinAddr: 0x3800, symSize: 0x0 }
  - { offsetInCU: 0x706, offset: 0x706, size: 0x8, addend: 0x0, symName: _ts_parse_actions, symObjAddr: 0x1ABE, symBinAddr: 0x3A72, symSize: 0x0 }
  - { offsetInCU: 0x727, offset: 0x727, size: 0x8, addend: 0x0, symName: _ts_symbol_names, symObjAddr: 0x1F70, symBinAddr: 0x40E0, symSize: 0x0 }
  - { offsetInCU: 0x749, offset: 0x749, size: 0x8, addend: 0x0, symName: _ts_field_names, symObjAddr: 0x2088, symBinAddr: 0x41F8, symSize: 0x0 }
  - { offsetInCU: 0x76B, offset: 0x76B, size: 0x8, addend: 0x0, symName: _ts_field_map_slices, symObjAddr: 0x18D0, symBinAddr: 0x3884, symSize: 0x0 }
  - { offsetInCU: 0x78D, offset: 0x78D, size: 0x8, addend: 0x0, symName: _ts_field_map_entries, symObjAddr: 0x18D8, symBinAddr: 0x388C, symSize: 0x0 }
  - { offsetInCU: 0x7AE, offset: 0x7AE, size: 0x8, addend: 0x0, symName: _ts_symbol_metadata, symObjAddr: 0x18DC, symBinAddr: 0x3890, symSize: 0x0 }
  - { offsetInCU: 0x7CF, offset: 0x7CF, size: 0x8, addend: 0x0, symName: _ts_symbol_map, symObjAddr: 0x1946, symBinAddr: 0x38FA, symSize: 0x0 }
  - { offsetInCU: 0x7F1, offset: 0x7F1, size: 0x8, addend: 0x0, symName: _ts_non_terminal_alias_map, symObjAddr: 0x198C, symBinAddr: 0x3940, symSize: 0x0 }
  - { offsetInCU: 0x813, offset: 0x813, size: 0x8, addend: 0x0, symName: _ts_alias_sequences, symObjAddr: 0x198E, symBinAddr: 0x3942, symSize: 0x0 }
  - { offsetInCU: 0x83B, offset: 0x83B, size: 0x8, addend: 0x0, symName: _ts_lex_modes, symObjAddr: 0x19A6, symBinAddr: 0x395A, symSize: 0x0 }
  - { offsetInCU: 0x86C, offset: 0x86C, size: 0x8, addend: 0x0, symName: _ts_lex, symObjAddr: 0xC, symBinAddr: 0x1FC0, symSize: 0xF2C }
...
